version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce_db_container
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: gizlisifre
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U furkan -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: ecommerce_web_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/ecommerce_db
      DB_USER: furkan
      DB_PASS: gizlisifre
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
